//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBranch
    {
        public int Id { get; set; }
        public Nullable<int> BankId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Address { get; set; }
    }
}
