//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankSolvenciesUpdateLog
    {
        public long Id { get; set; }
        public Nullable<long> BankSolvencyId { get; set; }
        public Nullable<long> CheckListId { get; set; }
        public Nullable<System.DateTime> SolvencyDate { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string BusinessAddress { get; set; }
        public Nullable<System.DateTime> NewSolvencyDate { get; set; }
        public Nullable<int> NewBankId { get; set; }
        public Nullable<int> NewBranchId { get; set; }
        public string NewAccountNo { get; set; }
        public string NewAccountName { get; set; }
        public string NewBusinessAddress { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdateName { get; set; }
    }
}
