//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardImage
    {
        public long Id { get; set; }
        public string ImageUrl { get; set; }
        public string ImageDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPopUp { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
    }
}
