//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorOrder
    {
        public long Id { get; set; }
        public string DistributorCode { get; set; }
        public decimal TotalPrice { get; set; }
        public long AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> NsmUpdatedby { get; set; }
        public Nullable<System.DateTime> NsmApprovedDate { get; set; }
        public Nullable<long> LogisticUpdatedBy { get; set; }
        public Nullable<System.DateTime> LogisticCompletedDate { get; set; }
    }
}
