//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor
    {
        public long Id { get; set; }
        public string DistributorNameCellCom { get; set; }
        public string DigitechCode { get; set; }
        public Nullable<long> ZoneId { get; set; }
        public string Zone { get; set; }
        public string ImportCode { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> DistributorTypeId { get; set; }
        public Nullable<int> ProductBrandId { get; set; }
        public Nullable<long> UpazilaId { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public Nullable<long> DivisionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
