//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorOthersInformationUpdateLog
    {
        public long Id { get; set; }
        public Nullable<long> DistributorOtherInformationId { get; set; }
        public Nullable<long> CheckListId { get; set; }
        public string DirectorNID_No { get; set; }
        public string NID_File { get; set; }
        public string DirectorPhoto { get; set; }
        public Nullable<bool> IsDirectorSealedAndSigned { get; set; }
        public string NomineeNID_No { get; set; }
        public string NomineeNID_File { get; set; }
        public Nullable<bool> IsSignedByNominee { get; set; }
        public Nullable<bool> IsSignedNomineeNIDByDirector { get; set; }
        public string NomineePhoto { get; set; }
        public Nullable<bool> IsNomineePhotoSignedByNominee { get; set; }
        public Nullable<bool> IsNomineePhotoSignedByDirector { get; set; }
        public Nullable<int> NomineeChequeBank { get; set; }
        public Nullable<int> NomineeBankBranch { get; set; }
        public string NomineeAccountName { get; set; }
        public string NomineeAccountNo { get; set; }
        public string NomineeChequeNo { get; set; }
        public Nullable<decimal> NomineeChequeAmount { get; set; }
        public Nullable<bool> NomineeMICR_Cheque { get; set; }
        public string MomineeMICR_ChequeFile { get; set; }
        public Nullable<System.DateTime> DistributorShopAgreementDate { get; set; }
        public Nullable<System.DateTime> DistributorShopAgreementEndDate { get; set; }
        public Nullable<bool> IsShopOwnedByDistributor { get; set; }
        public string NewDirectorNID_No { get; set; }
        public string NewNID_File { get; set; }
        public string NewDirectorPhoto { get; set; }
        public Nullable<bool> NewIsDirectorSealedAndSigned { get; set; }
        public string NewNomineeNID_No { get; set; }
        public string NewNomineeNID_File { get; set; }
        public Nullable<bool> NewIsSignedByNominee { get; set; }
        public Nullable<bool> NewIsSignedNomineeNIDByDirector { get; set; }
        public string NewNomineePhoto { get; set; }
        public Nullable<bool> NewIsNomineePhotoSignedByNominee { get; set; }
        public Nullable<bool> NewIsNomineePhotoSignedByDirector { get; set; }
        public Nullable<int> NewNomineeChequeBank { get; set; }
        public Nullable<int> NewNomineeBankBranch { get; set; }
        public string NewNomineeAccountName { get; set; }
        public string NewNomineeAccountNo { get; set; }
        public string NewNomineeChequeNo { get; set; }
        public Nullable<decimal> NewNomineeChequeAmount { get; set; }
        public Nullable<bool> NewNomineeMICR_Cheque { get; set; }
        public string NewMomineeMICR_ChequeFile { get; set; }
        public Nullable<System.DateTime> NewDistributorShopAgreementDate { get; set; }
        public Nullable<System.DateTime> NewDistributorShopAgreementEndDate { get; set; }
        public Nullable<bool> NewIsShopOwnedByDistributor { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdateName { get; set; }
    }
}
