//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorCheckList
    {
        public DistributorCheckList()
        {
            this.BankSolvencies = new HashSet<BankSolvency>();
            this.DistributorOthersInformations = new HashSet<DistributorOthersInformation>();
            this.DistributorPersonalInformations = new HashSet<DistributorPersonalInformation>();
            this.MemorandumOfAgreements = new HashSet<MemorandumOfAgreement>();
            this.MemorandumOfCheques = new HashSet<MemorandumOfCheque>();
            this.TaxIdentities = new HashSet<TaxIdentity>();
            this.TradeLicenses = new HashSet<TradeLicens>();
            this.ValueAddedTaxes = new HashSet<ValueAddedTax>();
        }
    
        public long Id { get; set; }
        public string DealerCode { get; set; }
        public Nullable<bool> IsCreationApproved { get; set; }
        public Nullable<long> CreationApprovedBy { get; set; }
        public Nullable<System.DateTime> CreationApprovedDate { get; set; }
        public Nullable<bool> IsTheDealerBlocked { get; set; }
        public Nullable<bool> IsTemporaryOpen { get; set; }
        public Nullable<System.DateTime> TempOpenDate { get; set; }
        public Nullable<System.DateTime> TempExpireDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdateName { get; set; }
    
        public virtual ICollection<BankSolvency> BankSolvencies { get; set; }
        public virtual ICollection<DistributorOthersInformation> DistributorOthersInformations { get; set; }
        public virtual ICollection<DistributorPersonalInformation> DistributorPersonalInformations { get; set; }
        public virtual ICollection<MemorandumOfAgreement> MemorandumOfAgreements { get; set; }
        public virtual ICollection<MemorandumOfCheque> MemorandumOfCheques { get; set; }
        public virtual ICollection<TaxIdentity> TaxIdentities { get; set; }
        public virtual ICollection<TradeLicens> TradeLicenses { get; set; }
        public virtual ICollection<ValueAddedTax> ValueAddedTaxes { get; set; }
    }
}
