//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorPersonalInformation
    {
        public long Id { get; set; }
        public long CheckListId { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DistributorDOB { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string BrothersName { get; set; }
        public string SistersName { get; set; }
        public string FathersOccupation { get; set; }
        public string MothersOccupation { get; set; }
        public string BrothersOccupation { get; set; }
        public string SistersOccupation { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public string PropertyDetail { get; set; }
        public string EducationDetail { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public string EmergencyName1 { get; set; }
        public string EmergencyAddress1 { get; set; }
        public string EmergencyNumber1 { get; set; }
        public string EmergencyName2 { get; set; }
        public string EmergencyAddress2 { get; set; }
        public string EmergencyNumber2 { get; set; }
        public string BusinessType { get; set; }
        public string PartyCategory { get; set; }
        public Nullable<long> ZoneId { get; set; }
        public string ZoneName { get; set; }
        public string BusinessAddress { get; set; }
        public string ShopPictureUrl { get; set; }
        public string ExperienceDetail { get; set; }
        public Nullable<double> RunningBusinessDetail_OthersAge { get; set; }
        public Nullable<decimal> RunningBusinessDetail_OthersInvestment { get; set; }
        public Nullable<double> RunningBusinessDetail_WaltonAge { get; set; }
        public Nullable<decimal> RunningBusinessDetail_WaltonInvestment { get; set; }
        public string Reference { get; set; }
        public string Ownership { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UpdateName { get; set; }
    
        public virtual DistributorCheckList DistributorCheckList { get; set; }
    }
}
