//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorOrderDetail
    {
        public long Id { get; set; }
        public long DistributorOrderId { get; set; }
        public string ModelName { get; set; }
        public string Color { get; set; }
        public decimal UnitPrice { get; set; }
        public int RequestedQuantity { get; set; }
        public Nullable<int> NsmApprovedQty { get; set; }
        public Nullable<int> LogisticsApprovedQty { get; set; }
        public bool IsDeleted { get; set; }
        public string AddedRole { get; set; }
        public long AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
    }
}
