//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncentiveDistribution_Back20210627
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string ModelName { get; set; }
        public decimal TotalIncentiveAmount { get; set; }
        public decimal DealerAmount { get; set; }
        public decimal RetailerAmount { get; set; }
        public decimal SRAmount { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long AddedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    }
}
