//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketShare
    {
        public long Id { get; set; }
        public Nullable<long> ZoneId { get; set; }
        public Nullable<long> BrandId { get; set; }
        public Nullable<decimal> ShareAmount { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> YearNumber { get; set; }
    }
}
