//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemorandumOfAgreement
    {
        public MemorandumOfAgreement()
        {
            this.MOA_Stamps = new HashSet<MOA_Stamps>();
        }
    
        public long Id { get; set; }
        public Nullable<long> CheckListId { get; set; }
        public Nullable<decimal> InvestmnetAmount { get; set; }
        public Nullable<System.DateTime> AgreementStartDate { get; set; }
        public Nullable<System.DateTime> AgreementEndDate { get; set; }
        public string StampNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string VendorId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UpdateName { get; set; }
    
        public virtual DistributorCheckList DistributorCheckList { get; set; }
        public virtual ICollection<MOA_Stamps> MOA_Stamps { get; set; }
    }
}
