//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemorandumOfChequeUpdateLog
    {
        public long Id { get; set; }
        public Nullable<long> MemorandumOfChequeId { get; set; }
        public Nullable<long> CheckListId { get; set; }
        public string DistributorCode { get; set; }
        public string StampNo { get; set; }
        public string StampType { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string VendorId { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string AccountStatement { get; set; }
        public string CheueNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> MICR { get; set; }
        public string ChequeAttachment { get; set; }
        public string NewDistributorCode { get; set; }
        public string NewStampNo { get; set; }
        public Nullable<System.DateTime> NewPurchaseDate { get; set; }
        public string NewVendorId { get; set; }
        public Nullable<System.DateTime> NewChequeDate { get; set; }
        public Nullable<int> NewBankId { get; set; }
        public Nullable<int> NewBranchId { get; set; }
        public string NewAccountNo { get; set; }
        public string NewCheueNo { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public Nullable<bool> NewMICR { get; set; }
        public string NewChequeAttachment { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdateName { get; set; }
    }
}
