//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemorandumOfAgreementUpdateLog
    {
        public long Id { get; set; }
        public Nullable<long> MemorandumOfAgreementId { get; set; }
        public Nullable<long> CheckListId { get; set; }
        public Nullable<decimal> InvestmnetAmount { get; set; }
        public Nullable<System.DateTime> AgreementStartDate { get; set; }
        public Nullable<System.DateTime> AgreementEndDate { get; set; }
        public string StampNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string VendorId { get; set; }
        public Nullable<decimal> NewInvestmnetAmount { get; set; }
        public Nullable<System.DateTime> NewAgreementStartDate { get; set; }
        public Nullable<System.DateTime> NewAgreementEndDate { get; set; }
        public string NewStampNo { get; set; }
        public Nullable<System.DateTime> NewPurchaseDate { get; set; }
        public string NewVendorId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UpdateName { get; set; }
    }
}
