//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisPerson
    {
        public long Id { get; set; }
        public string DealerName { get; set; }
        public string DealerDigitechCode { get; set; }
        public string Zone { get; set; }
        public string MisName { get; set; }
        public string MobileNumber { get; set; }
        public string PaymentNumber { get; set; }
        public string isMIS { get; set; }
        public string isDSR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> DeletedBy { get; set; }
    }
}
