//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisUpdateLog
    {
        public long Id { get; set; }
        public Nullable<long> MISId { get; set; }
        public string OldName { get; set; }
        public string OldPhone { get; set; }
        public string OldPayment { get; set; }
        public string OldDealerCode { get; set; }
        public string OldZone { get; set; }
        public string NewName { get; set; }
        public string NewPhone { get; set; }
        public string NewPayment { get; set; }
        public string NewDealerCode { get; set; }
        public string NewZone { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
    }
}
