//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public long Id { get; set; }
        public string DealerName { get; set; }
        public string ImportCode { get; set; }
        public string DigiTechCode { get; set; }
        public string Zone { get; set; }
        public string ZoneWithoutSpace { get; set; }
        public string PhoneNumber { get; set; }
        public string DistributorType { get; set; }
    }
}
