//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerDistribution
    {
        public long Id { get; set; }
        public Nullable<long> RetailerId { get; set; }
        public Nullable<long> RetailerOrderDetailId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string ImeiOne { get; set; }
        public string ImeiTwo { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
        public Nullable<bool> IsSoldOut { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnDetail { get; set; }
        public Nullable<bool> IsReturnApprovedInApi { get; set; }
        public Nullable<System.DateTime> ReturnApproveDateApi { get; set; }
    
        public virtual RetailerOrderDetail RetailerOrderDetail { get; set; }
    }
}
