//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerOrderDetail
    {
        public RetailerOrderDetail()
        {
            this.RetailerDistributions = new HashSet<RetailerDistribution>();
        }
    
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> ProductTypeId { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<int> GivenQuantity { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> OrderTotalPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string DiscountType { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual ICollection<RetailerDistribution> RetailerDistributions { get; set; }
        public virtual RetailerOrder RetailerOrder { get; set; }
    }
}
