//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerUpdateLog
    {
        public long Id { get; set; }
        public long RetailerId { get; set; }
        public string NewAddress { get; set; }
        public string NewPhoneNumber { get; set; }
        public string NewPaymentNumber { get; set; }
        public string NewPaymentType { get; set; }
        public long RequestedBy { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public Nullable<long> RecommendBy { get; set; }
        public Nullable<System.DateTime> RecommendDate { get; set; }
        public Nullable<long> ApproveBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    }
}
