//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerPromotionalWinning
    {
        public long Id { get; set; }
        public Nullable<long> WinnerId { get; set; }
        public Nullable<long> OfferId { get; set; }
        public Nullable<long> TossId { get; set; }
        public string CustomerMsg { get; set; }
        public string SellerMsg { get; set; }
        public string ImeiOne { get; set; }
        public string ImeiTwo { get; set; }
        public string ModelName { get; set; }
        public string Brand { get; set; }
        public string CustomerPhone { get; set; }
        public string SellerPhone { get; set; }
        public string DealerCode { get; set; }
        public Nullable<long> RetailerId { get; set; }
        public string RetailerName { get; set; }
        public string RetailerPhoneNumber { get; set; }
        public Nullable<System.DateTime> MsgResponseDate { get; set; }
        public Nullable<bool> IsSmsSent { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdateName { get; set; }
        public Nullable<bool> IsCustomerGotSms { get; set; }
        public Nullable<bool> IsDealerGotSms { get; set; }
        public string CustomerMsgId { get; set; }
        public string SellerMsgId { get; set; }
        public Nullable<long> RewardId { get; set; }
        public string RewardType { get; set; }
        public string RewardName { get; set; }
        public Nullable<decimal> RewardValue { get; set; }
    }
}
