//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerTransferLog
    {
        public long Id { get; set; }
        public long RetailerId { get; set; }
        public string FromDistributorCode { get; set; }
        public string ToDistributorCode { get; set; }
        public System.DateTime TransferDate { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestedBy { get; set; }
        public string TransferedBy { get; set; }
    }
}
