//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerOrder
    {
        public RetailerOrder()
        {
            this.RetailerOrderDetails = new HashSet<RetailerOrderDetail>();
        }
    
        public long Id { get; set; }
        public string SerialNo { get; set; }
        public Nullable<long> RetailerId { get; set; }
        public Nullable<long> SRId { get; set; }
        public string DealerCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual ICollection<RetailerOrderDetail> RetailerOrderDetails { get; set; }
    }
}
