//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTeam
    {
        public long Id { get; set; }
        public string EmpId { get; set; }
        public string Name { get; set; }
        public string Post { get; set; }
        public string Designation { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string InchargeId { get; set; }
        public string DeputyInchargeId { get; set; }
        public string TeamName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
