//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRUpdateLog
    {
        public long Id { get; set; }
        public long SrId { get; set; }
        public string PresentName { get; set; }
        public string NewName { get; set; }
        public string PresentEmail { get; set; }
        public string NewEmail { get; set; }
        public string PresentPhone { get; set; }
        public string NewPhone { get; set; }
        public string PresentPaymentType { get; set; }
        public string NewPaymentType { get; set; }
        public string PresentPaymentNumber { get; set; }
        public string NewPaymentNumber { get; set; }
        public long RequestedBy { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public Nullable<long> RecommendedBy { get; set; }
        public Nullable<System.DateTime> RecommendedDate { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
