//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDS.DAL.WdsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VarificationApproval
    {
        public long Id { get; set; }
        public Nullable<long> CheckListId { get; set; }
        public Nullable<long> VarificationEntityId { get; set; }
        public string VarificationEntityDesc { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<bool> IsDeclined { get; set; }
        public Nullable<System.DateTime> DeclinedDate { get; set; }
        public Nullable<long> DeclinedBy { get; set; }
        public string DeclinedRemarks { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UpdateName { get; set; }
    }
}
